version: '3.8'

services:
  app:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./src/modules/User:/var/www/html/modules/User:ro
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "59000:80"  # Map port 80 from Nginx to 59000 on the host
    volumes:
      - ./src:/var/www/html
      - ./src/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
